{{- if .Values.jobServiceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobServiceAccounts.triage }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hal-k8s-operator.labels" . | nindent 4 }}
    hal.dev/job-role: triage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobServiceAccounts.fix }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hal-k8s-operator.labels" . | nindent 4 }}
    hal.dev/job-role: fix
automountServiceAccountToken: false
{{- end }}
