{{- if and .Values.github.createSecret .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.triageSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hal-k8s-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.secretKey }}: {{ .Values.github.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.fixSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hal-k8s-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.secretKey }}: {{ .Values.github.token | quote }}
{{- end }}
